FROM node:18-alpine
WORKDIR /app

ENV NODE_ENV=development

# Install all dependencies for development
COPY package.json package-lock.json* ./
RUN npm install \
    && npm cache clean --force

COPY tsconfig.json ./
COPY src ./src

EXPOSE 3847

USER node

CMD ["npm", "run", "dev"]
